version: '3.4'
services:
  api:
    image: tom-cluise-rec-1.0:latest
    build: .
    ports:
      - "5000:5000"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=key.json
      - face_debug=False